version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - cd terraform
      - chmod 700 applyterraform.sh 

  build:
    commands:
      - ./applyterraform.sh